[2025-04-06T15:50:00.134+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-06T15:50:00.143+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: premier_league_data_pipeline.download_data_2021_22 manual__2025-04-06T14:34:57.308181+00:00 [queued]>
[2025-04-06T15:50:00.148+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: premier_league_data_pipeline.download_data_2021_22 manual__2025-04-06T14:34:57.308181+00:00 [queued]>
[2025-04-06T15:50:00.148+0100] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-06T15:50:00.160+0100] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): download_data_2021_22> on 2025-04-06 14:34:57.308181+00:00
[2025-04-06T15:50:00.164+0100] {standard_task_runner.py:72} INFO - Started process 40466 to run task
[2025-04-06T15:50:00.167+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'premier_league_data_pipeline', 'download_data_2021_22', 'manual__2025-04-06T14:34:57.308181+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/premier_league_dag.py', '--cfg-path', '/tmp/tmp7fv9ldso']
[2025-04-06T15:50:00.168+0100] {standard_task_runner.py:105} INFO - Job 28: Subtask download_data_2021_22
[2025-04-06T15:50:00.196+0100] {task_command.py:467} INFO - Running <TaskInstance: premier_league_data_pipeline.download_data_2021_22 manual__2025-04-06T14:34:57.308181+00:00 [running]> on host dell-Latitude-5480
[2025-04-06T15:50:00.249+0100] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Victory' AIRFLOW_CTX_DAG_ID='premier_league_data_pipeline' AIRFLOW_CTX_TASK_ID='download_data_2021_22' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T14:34:57.308181+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T14:34:57.308181+00:00'
[2025-04-06T15:50:00.250+0100] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-06T15:50:00.250+0100] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-06T15:50:00.251+0100] {logging_mixin.py:190} INFO - Current task name:download_data_2021_22 state:running start_date:2025-04-06 14:50:00.143442+00:00
[2025-04-06T15:50:00.251+0100] {logging_mixin.py:190} INFO - Dag name:premier_league_data_pipeline and current dag run status:running
[2025-04-06T15:50:00.251+0100] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-06T15:50:21.986+0100] {logging_mixin.py:190} INFO - No cookies popup found, continuing...
[2025-04-06T15:50:42.037+0100] {logging_mixin.py:190} INFO - Error opening dropdown: Message: 
Stacktrace:
#0 0x5600e40edffa <unknown>
#1 0x5600e3bac970 <unknown>
#2 0x5600e3bfe385 <unknown>
#3 0x5600e3bfe5b1 <unknown>
#4 0x5600e3c4d3c4 <unknown>
#5 0x5600e3c242bd <unknown>
#6 0x5600e3c4a70c <unknown>
#7 0x5600e3c24063 <unknown>
#8 0x5600e3bf0328 <unknown>
#9 0x5600e3bf1491 <unknown>
#10 0x5600e40b542b <unknown>
#11 0x5600e40b92ec <unknown>
#12 0x5600e409ca22 <unknown>
#13 0x5600e40b9e64 <unknown>
#14 0x5600e4080bef <unknown>
#15 0x5600e40dc558 <unknown>
#16 0x5600e40dc736 <unknown>
#17 0x5600e40ece76 <unknown>
#18 0x7f242f899ac3 <unknown>
[2025-04-06T15:51:02.115+0100] {logging_mixin.py:190} INFO - Error selecting game week 1: Message: 
Stacktrace:
#0 0x5600e40edffa <unknown>
#1 0x5600e3bac970 <unknown>
#2 0x5600e3bfe385 <unknown>
#3 0x5600e3bfe5b1 <unknown>
#4 0x5600e3c4d3c4 <unknown>
#5 0x5600e3c242bd <unknown>
#6 0x5600e3c4a70c <unknown>
#7 0x5600e3c24063 <unknown>
#8 0x5600e3bf0328 <unknown>
#9 0x5600e3bf1491 <unknown>
#10 0x5600e40b542b <unknown>
#11 0x5600e40b92ec <unknown>
#12 0x5600e409ca22 <unknown>
#13 0x5600e40b9e64 <unknown>
#14 0x5600e4080bef <unknown>
#15 0x5600e40dc558 <unknown>
#16 0x5600e40dc736 <unknown>
#17 0x5600e40ece76 <unknown>
#18 0x7f242f899ac3 <unknown>
[2025-04-06T15:51:02.329+0100] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/airflow/dags/scripts/download_data.py", line 14, in download_data
    df = crawler.run(start_game_week, end_game_week)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/airflow/dags/scripts/crawler.py", line 152, in run
    dropdown = self.wait.until(EC.presence_of_element_located((By.XPATH, dropdown_xpath)))
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 137, in until
    value = method(self._driver)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/support/expected_conditions.py", line 110, in _predicate
    return driver.find_element(*locator)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 898, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: 'value' must be a string
  (Session info: chrome=134.0.6998.165)
Stacktrace:
#0 0x5600e40edffa <unknown>
#1 0x5600e3bac970 <unknown>
#2 0x5600e3bfdd8d <unknown>
#3 0x5600e3bfe5b1 <unknown>
#4 0x5600e3c4d3c4 <unknown>
#5 0x5600e3c242bd <unknown>
#6 0x5600e3c4a70c <unknown>
#7 0x5600e3c24063 <unknown>
#8 0x5600e3bf0328 <unknown>
#9 0x5600e3bf1491 <unknown>
#10 0x5600e40b542b <unknown>
#11 0x5600e40b92ec <unknown>
#12 0x5600e409ca22 <unknown>
#13 0x5600e40b9e64 <unknown>
#14 0x5600e4080bef <unknown>
#15 0x5600e40dc558 <unknown>
#16 0x5600e40dc736 <unknown>
#17 0x5600e40ece76 <unknown>
#18 0x7f242f899ac3 <unknown>

[2025-04-06T15:51:02.341+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-06T15:51:02.342+0100] {logging_mixin.py:190} INFO - Task start:2025-04-06 14:50:00.143442+00:00 end:2025-04-06 14:51:02.341141+00:00 duration:62.197699
[2025-04-06T15:51:02.342+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): download_data_2021_22> dag:<DAG: premier_league_data_pipeline> dagrun:<DagRun premier_league_data_pipeline @ 2025-04-06 14:34:57.308181+00:00: manual__2025-04-06T14:34:57.308181+00:00, state:running, queued_at: 2025-04-06 14:34:57.327913+00:00. externally triggered: True>
[2025-04-06T15:51:02.342+0100] {logging_mixin.py:190} INFO - Failure caused by Message: invalid argument: 'value' must be a string
  (Session info: chrome=134.0.6998.165)
Stacktrace:
#0 0x5600e40edffa <unknown>
#1 0x5600e3bac970 <unknown>
#2 0x5600e3bfdd8d <unknown>
#3 0x5600e3bfe5b1 <unknown>
#4 0x5600e3c4d3c4 <unknown>
#5 0x5600e3c242bd <unknown>
#6 0x5600e3c4a70c <unknown>
#7 0x5600e3c24063 <unknown>
#8 0x5600e3bf0328 <unknown>
#9 0x5600e3bf1491 <unknown>
#10 0x5600e40b542b <unknown>
#11 0x5600e40b92ec <unknown>
#12 0x5600e409ca22 <unknown>
#13 0x5600e40b9e64 <unknown>
#14 0x5600e4080bef <unknown>
#15 0x5600e40dc558 <unknown>
#16 0x5600e40dc736 <unknown>
#17 0x5600e40ece76 <unknown>
#18 0x7f242f899ac3 <unknown>
[2025-04-06T15:51:02.343+0100] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=premier_league_data_pipeline, task_id=download_data_2021_22, run_id=manual__2025-04-06T14:34:57.308181+00:00, execution_date=20250406T143457, start_date=20250406T145000, end_date=20250406T145102
[2025-04-06T15:51:02.369+0100] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-06T15:51:02.369+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 28 for task download_data_2021_22 (Message: invalid argument: 'value' must be a string
  (Session info: chrome=134.0.6998.165)
Stacktrace:
#0 0x5600e40edffa <unknown>
#1 0x5600e3bac970 <unknown>
#2 0x5600e3bfdd8d <unknown>
#3 0x5600e3bfe5b1 <unknown>
#4 0x5600e3c4d3c4 <unknown>
#5 0x5600e3c242bd <unknown>
#6 0x5600e3c4a70c <unknown>
#7 0x5600e3c24063 <unknown>
#8 0x5600e3bf0328 <unknown>
#9 0x5600e3bf1491 <unknown>
#10 0x5600e40b542b <unknown>
#11 0x5600e40b92ec <unknown>
#12 0x5600e409ca22 <unknown>
#13 0x5600e40b9e64 <unknown>
#14 0x5600e4080bef <unknown>
#15 0x5600e40dc558 <unknown>
#16 0x5600e40dc736 <unknown>
#17 0x5600e40ece76 <unknown>
#18 0x7f242f899ac3 <unknown>
; 40466)
Traceback (most recent call last):
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/airflow/dags/scripts/download_data.py", line 14, in download_data
    df = crawler.run(start_game_week, end_game_week)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/airflow/dags/scripts/crawler.py", line 152, in run
    dropdown = self.wait.until(EC.presence_of_element_located((By.XPATH, dropdown_xpath)))
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 137, in until
    value = method(self._driver)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/support/expected_conditions.py", line 110, in _predicate
    return driver.find_element(*locator)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 898, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: 'value' must be a string
  (Session info: chrome=134.0.6998.165)
Stacktrace:
#0 0x5600e40edffa <unknown>
#1 0x5600e3bac970 <unknown>
#2 0x5600e3bfdd8d <unknown>
#3 0x5600e3bfe5b1 <unknown>
#4 0x5600e3c4d3c4 <unknown>
#5 0x5600e3c242bd <unknown>
#6 0x5600e3c4a70c <unknown>
#7 0x5600e3c24063 <unknown>
#8 0x5600e3bf0328 <unknown>
#9 0x5600e3bf1491 <unknown>
#10 0x5600e40b542b <unknown>
#11 0x5600e40b92ec <unknown>
#12 0x5600e409ca22 <unknown>
#13 0x5600e40b9e64 <unknown>
#14 0x5600e4080bef <unknown>
#15 0x5600e40dc558 <unknown>
#16 0x5600e40dc736 <unknown>
#17 0x5600e40ece76 <unknown>
#18 0x7f242f899ac3 <unknown>

[2025-04-06T15:51:02.387+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-06T15:51:02.410+0100] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-06T15:51:02.411+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
