[2025-03-31T21:30:53.616+0000] {processor.py:186} INFO - Started process (PID=971) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:30:53.617+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:30:53.620+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:30:53.619+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:30:53.642+0000] {processor.py:925} INFO - DAG(s) 'premier_league_data_pipeline' retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:30:53.796+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:30:53.795+0000] {override.py:1912} INFO - Created Permission View: can edit on DAG:premier_league_data_pipeline
[2025-03-31T21:30:53.813+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:30:53.813+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG:premier_league_data_pipeline
[2025-03-31T21:30:53.824+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:30:53.824+0000] {override.py:1912} INFO - Created Permission View: can read on DAG:premier_league_data_pipeline
[2025-03-31T21:30:53.836+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:30:53.836+0000] {override.py:1912} INFO - Created Permission View: menu access on DAG Run:premier_league_data_pipeline
[2025-03-31T21:30:53.847+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:30:53.846+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG Run:premier_league_data_pipeline
[2025-03-31T21:30:53.859+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:30:53.858+0000] {override.py:1912} INFO - Created Permission View: can read on DAG Run:premier_league_data_pipeline
[2025-03-31T21:30:53.870+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:30:53.869+0000] {override.py:1912} INFO - Created Permission View: can create on DAG Run:premier_league_data_pipeline
[2025-03-31T21:30:53.871+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:30:53.870+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-31T21:30:53.888+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:30:53.888+0000] {dag.py:3262} INFO - Creating ORM DAG for premier_league_data_pipeline
[2025-03-31T21:30:53.908+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:30:53.908+0000] {dag.py:4180} INFO - Setting next_dagrun for premier_league_data_pipeline to 2026-01-01 00:00:00+00:00, run_after=2027-01-01 00:00:00+00:00
[2025-03-31T21:30:53.933+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.329 seconds
[2025-03-31T21:30:57.660+0000] {processor.py:186} INFO - Started process (PID=972) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:30:57.662+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:30:57.665+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:30:57.664+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:30:57.686+0000] {processor.py:925} INFO - DAG(s) 'premier_league_data_pipeline' retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:30:57.705+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:30:57.704+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-31T21:30:57.744+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:30:57.744+0000] {dag.py:4180} INFO - Setting next_dagrun for premier_league_data_pipeline to 2026-01-01 00:00:00+00:00, run_after=2027-01-01 00:00:00+00:00
[2025-03-31T21:30:57.776+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.125 seconds
[2025-03-31T21:31:28.131+0000] {processor.py:186} INFO - Started process (PID=1036) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:31:28.133+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:31:28.135+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:31:28.135+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:31:28.182+0000] {processor.py:925} INFO - DAG(s) 'premier_league_data_pipeline' retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:31:28.268+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:31:28.267+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-31T21:31:28.367+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:31:28.367+0000] {dag.py:4180} INFO - Setting next_dagrun for premier_league_data_pipeline to 2026-01-01 00:00:00+00:00, run_after=2027-01-01 00:00:00+00:00
[2025-03-31T21:31:28.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.378 seconds
[2025-03-31T21:32:00.812+0000] {processor.py:186} INFO - Started process (PID=1092) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:32:00.816+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:32:00.821+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:32:00.821+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:32:00.874+0000] {processor.py:925} INFO - DAG(s) 'premier_league_data_pipeline' retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:32:01.000+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:32:00.989+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-31T21:32:01.107+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:32:01.107+0000] {dag.py:4180} INFO - Setting next_dagrun for premier_league_data_pipeline to 2026-01-01 00:00:00+00:00, run_after=2027-01-01 00:00:00+00:00
[2025-03-31T21:32:01.160+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.362 seconds
[2025-03-31T21:32:31.980+0000] {processor.py:186} INFO - Started process (PID=1155) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:32:31.984+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:32:31.987+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:32:31.987+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:32:32.014+0000] {processor.py:925} INFO - DAG(s) 'premier_league_data_pipeline' retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:32:32.053+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:32:32.053+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-31T21:32:32.114+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:32:32.113+0000] {dag.py:4180} INFO - Setting next_dagrun for premier_league_data_pipeline to 2026-01-01 00:00:00+00:00, run_after=2027-01-01 00:00:00+00:00
[2025-03-31T21:32:32.156+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.191 seconds
[2025-03-31T21:33:02.740+0000] {processor.py:186} INFO - Started process (PID=1215) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:33:02.741+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:33:02.744+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:33:02.743+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:33:02.775+0000] {processor.py:925} INFO - DAG(s) 'premier_league_data_pipeline' retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:33:02.813+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:33:02.812+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-31T21:33:02.856+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:33:02.856+0000] {dag.py:4180} INFO - Setting next_dagrun for premier_league_data_pipeline to 2026-01-01 00:00:00+00:00, run_after=2027-01-01 00:00:00+00:00
[2025-03-31T21:33:02.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.155 seconds
[2025-03-31T21:33:33.463+0000] {processor.py:186} INFO - Started process (PID=1278) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:33:33.464+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:33:33.467+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:33:33.467+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:33:33.493+0000] {processor.py:925} INFO - DAG(s) 'premier_league_data_pipeline' retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:33:33.527+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:33:33.526+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-31T21:33:33.574+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:33:33.574+0000] {dag.py:4180} INFO - Setting next_dagrun for premier_league_data_pipeline to 2026-01-01 00:00:00+00:00, run_after=2027-01-01 00:00:00+00:00
[2025-03-31T21:33:33.604+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.152 seconds
[2025-03-31T21:34:03.729+0000] {processor.py:186} INFO - Started process (PID=1342) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:34:03.732+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:34:03.737+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:34:03.736+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:34:03.832+0000] {processor.py:925} INFO - DAG(s) 'premier_league_data_pipeline' retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:34:03.929+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:34:03.928+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-31T21:34:04.005+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:34:04.005+0000] {dag.py:4180} INFO - Setting next_dagrun for premier_league_data_pipeline to 2026-01-01 00:00:00+00:00, run_after=2027-01-01 00:00:00+00:00
[2025-03-31T21:34:04.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.341 seconds
[2025-03-31T21:34:34.281+0000] {processor.py:186} INFO - Started process (PID=1405) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:34:34.284+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:34:34.289+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:34:34.288+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:34:34.321+0000] {processor.py:925} INFO - DAG(s) 'premier_league_data_pipeline' retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:34:34.383+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:34:34.382+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-31T21:34:34.440+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:34:34.440+0000] {dag.py:4180} INFO - Setting next_dagrun for premier_league_data_pipeline to 2026-01-01 00:00:00+00:00, run_after=2027-01-01 00:00:00+00:00
[2025-03-31T21:34:34.490+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.222 seconds
[2025-03-31T21:35:04.598+0000] {processor.py:186} INFO - Started process (PID=1468) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:35:04.600+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:35:04.604+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:35:04.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:35:04.642+0000] {processor.py:925} INFO - DAG(s) 'premier_league_data_pipeline' retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:35:04.683+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:35:04.683+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-31T21:35:04.741+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:35:04.741+0000] {dag.py:4180} INFO - Setting next_dagrun for premier_league_data_pipeline to 2026-01-01 00:00:00+00:00, run_after=2027-01-01 00:00:00+00:00
[2025-03-31T21:35:04.789+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.205 seconds
[2025-03-31T21:35:35.767+0000] {processor.py:186} INFO - Started process (PID=1532) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:35:35.768+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:35:35.771+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:35:35.771+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:35:35.799+0000] {processor.py:925} INFO - DAG(s) 'premier_league_data_pipeline' retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:35:35.831+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:35:35.831+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-31T21:35:35.878+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:35:35.877+0000] {dag.py:4180} INFO - Setting next_dagrun for premier_league_data_pipeline to 2026-01-01 00:00:00+00:00, run_after=2027-01-01 00:00:00+00:00
[2025-03-31T21:35:35.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.148 seconds
[2025-03-31T21:36:06.581+0000] {processor.py:186} INFO - Started process (PID=1596) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:36:06.583+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:36:06.587+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:36:06.587+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:36:06.625+0000] {processor.py:925} INFO - DAG(s) 'premier_league_data_pipeline' retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:36:06.675+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:36:06.675+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-31T21:36:06.728+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:36:06.728+0000] {dag.py:4180} INFO - Setting next_dagrun for premier_league_data_pipeline to 2026-01-01 00:00:00+00:00, run_after=2027-01-01 00:00:00+00:00
[2025-03-31T21:36:06.769+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.204 seconds
[2025-03-31T21:36:54.849+0000] {processor.py:186} INFO - Started process (PID=1648) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:36:54.859+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:36:54.865+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:36:54.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:36:54.915+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:36:54.887+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:36:54.917+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:36:54.998+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.185 seconds
[2025-03-31T21:37:25.173+0000] {processor.py:186} INFO - Started process (PID=1710) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:37:25.178+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:37:25.194+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:37:25.193+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:37:25.216+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:37:25.212+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:37:25.218+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:37:25.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.170 seconds
[2025-03-31T21:37:56.044+0000] {processor.py:186} INFO - Started process (PID=1772) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:37:56.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:37:56.056+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:37:56.055+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:37:56.076+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:37:56.074+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:37:56.079+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:37:56.130+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.096 seconds
[2025-03-31T21:38:27.181+0000] {processor.py:186} INFO - Started process (PID=1836) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:38:27.183+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:38:27.188+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:38:27.188+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:38:27.302+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:38:27.297+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:38:27.305+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:38:27.380+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.225 seconds
[2025-03-31T21:39:48.935+0000] {processor.py:186} INFO - Started process (PID=1883) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:39:48.949+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:39:48.998+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:39:48.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:39:49.116+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:39:49.107+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:39:49.132+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:39:49.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.498 seconds
[2025-03-31T21:40:24.054+0000] {processor.py:186} INFO - Started process (PID=1945) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:40:24.058+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:40:24.064+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:40:24.063+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:40:24.095+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:40:24.088+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:40:24.098+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:40:24.284+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.258 seconds
[2025-03-31T21:42:03.533+0000] {processor.py:186} INFO - Started process (PID=1976) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:42:03.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:42:03.556+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:42:03.549+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:42:03.616+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:42:03.600+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:42:03.621+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:42:05.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 2.126 seconds
[2025-03-31T21:43:00.372+0000] {processor.py:186} INFO - Started process (PID=2032) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:43:00.375+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:43:00.383+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:43:00.380+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:43:00.394+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:43:00.392+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:43:00.396+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:43:00.441+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.084 seconds
[2025-03-31T21:43:44.190+0000] {processor.py:186} INFO - Started process (PID=2056) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:43:44.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:43:44.196+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:43:44.195+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:43:44.222+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:43:44.216+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:43:44.225+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:43:44.282+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.116 seconds
[2025-03-31T21:44:14.543+0000] {processor.py:186} INFO - Started process (PID=2115) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:44:14.545+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:44:14.547+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:44:14.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:44:14.570+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:44:14.565+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:44:14.572+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:44:14.611+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.079 seconds
[2025-03-31T21:44:45.005+0000] {processor.py:186} INFO - Started process (PID=2179) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:44:45.006+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:44:45.013+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:44:45.010+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:44:45.025+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:44:45.021+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:44:45.029+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:44:45.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.086 seconds
[2025-03-31T21:45:15.903+0000] {processor.py:186} INFO - Started process (PID=2243) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:45:15.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:45:15.909+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:45:15.908+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:45:15.923+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:45:15.921+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:45:15.925+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:45:16.005+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.120 seconds
[2025-03-31T21:45:47.320+0000] {processor.py:186} INFO - Started process (PID=2307) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:45:47.372+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:45:47.488+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:45:47.472+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:45:47.783+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:45:47.677+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:45:48.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:45:49.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 1.966 seconds
[2025-03-31T21:49:03.151+0000] {processor.py:186} INFO - Started process (PID=2317) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:49:03.201+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:49:03.384+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:49:03.374+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:49:04.163+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:49:04.145+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:49:04.167+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:49:05.066+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 2.039 seconds
[2025-03-31T21:49:35.457+0000] {processor.py:186} INFO - Started process (PID=2380) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:49:35.460+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:49:35.466+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:49:35.464+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:49:35.479+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:49:35.476+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:49:35.482+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:49:35.530+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.089 seconds
[2025-03-31T21:50:05.641+0000] {processor.py:186} INFO - Started process (PID=2444) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:50:05.643+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:50:05.645+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:50:05.645+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:50:05.653+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:50:05.651+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:50:05.654+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:50:05.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.049 seconds
[2025-03-31T21:50:36.340+0000] {processor.py:186} INFO - Started process (PID=2508) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:50:36.341+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:50:36.344+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:50:36.343+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:50:36.352+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:50:36.350+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:50:36.354+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:50:36.380+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.050 seconds
[2025-03-31T21:51:06.783+0000] {processor.py:186} INFO - Started process (PID=2572) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:51:06.785+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:51:06.788+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:51:06.788+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:51:06.797+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:51:06.795+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:51:06.800+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:51:06.832+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.061 seconds
[2025-03-31T21:53:28.770+0000] {processor.py:186} INFO - Started process (PID=2636) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:53:28.773+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:53:28.779+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:53:28.776+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:53:28.862+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:53:28.860+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:53:28.879+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:53:28.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.216 seconds
[2025-03-31T21:54:00.829+0000] {processor.py:186} INFO - Started process (PID=2699) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:54:00.832+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:54:00.835+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:54:00.835+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:54:00.896+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:54:00.890+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:54:00.910+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:54:00.992+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.199 seconds
[2025-03-31T21:55:10.124+0000] {processor.py:186} INFO - Started process (PID=2714) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:55:10.129+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:55:10.142+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:55:10.141+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:55:10.176+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:55:10.172+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:55:10.179+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:55:10.278+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.190 seconds
[2025-03-31T21:55:40.871+0000] {processor.py:186} INFO - Started process (PID=2776) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:55:40.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:55:40.884+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:55:40.883+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:55:40.906+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:55:40.898+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:55:40.907+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:55:41.011+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.158 seconds
[2025-03-31T21:56:11.123+0000] {processor.py:186} INFO - Started process (PID=2838) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:56:11.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:56:11.130+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:56:11.129+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:56:11.148+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:56:11.146+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:56:11.149+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:56:11.182+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.070 seconds
[2025-03-31T21:57:08.669+0000] {processor.py:186} INFO - Started process (PID=2857) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:57:08.671+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:57:08.674+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:57:08.673+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:57:08.727+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:57:08.724+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:57:08.730+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:57:08.799+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.145 seconds
[2025-03-31T21:57:41.003+0000] {processor.py:186} INFO - Started process (PID=2920) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:57:41.006+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:57:41.011+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:57:41.010+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:57:41.026+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:57:41.021+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.crawler import
                               ^
SyntaxError: invalid syntax
[2025-03-31T21:57:41.028+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:57:41.117+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.140 seconds
[2025-03-31T21:57:51.011+0000] {processor.py:186} INFO - Started process (PID=2963) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:57:51.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:57:51.016+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:57:51.015+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:57:51.032+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:57:51.030+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.download_data import
                                     ^
SyntaxError: invalid syntax
[2025-03-31T21:57:51.034+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:57:51.086+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.086 seconds
[2025-03-31T21:58:21.348+0000] {processor.py:186} INFO - Started process (PID=3009) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:58:21.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:58:21.371+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:58:21.370+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:58:21.447+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:58:21.445+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.download_data import
                                     ^
SyntaxError: invalid syntax
[2025-03-31T21:58:21.451+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:58:21.541+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.216 seconds
[2025-03-31T21:59:06.627+0000] {processor.py:186} INFO - Started process (PID=3054) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:59:06.633+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:59:06.637+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:59:06.636+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:59:06.693+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:59:06.679+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.download_data import
                                     ^
SyntaxError: invalid syntax
[2025-03-31T21:59:06.718+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:59:06.821+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.207 seconds
[2025-03-31T21:59:37.333+0000] {processor.py:186} INFO - Started process (PID=3115) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:59:37.335+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T21:59:37.338+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:59:37.337+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:59:37.347+0000] {logging_mixin.py:190} INFO - [2025-03-31T21:59:37.345+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.download_data import
                                     ^
SyntaxError: invalid syntax
[2025-03-31T21:59:37.348+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T21:59:37.391+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.068 seconds
[2025-03-31T22:00:07.655+0000] {processor.py:186} INFO - Started process (PID=3178) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:00:07.657+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:00:07.660+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:00:07.659+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:00:07.688+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:00:07.683+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.download_data import
                                     ^
SyntaxError: invalid syntax
[2025-03-31T22:00:07.690+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:00:07.737+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.096 seconds
[2025-03-31T22:00:37.800+0000] {processor.py:186} INFO - Started process (PID=3241) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:00:37.803+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:00:37.807+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:00:37.806+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:00:37.817+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:00:37.815+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.download_data import
                                     ^
SyntaxError: invalid syntax
[2025-03-31T22:00:37.819+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:00:37.871+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.084 seconds
[2025-03-31T22:01:08.731+0000] {processor.py:186} INFO - Started process (PID=3304) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:01:08.746+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:01:08.859+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:01:08.834+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:01:09.198+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:01:09.089+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.download_data import
                                     ^
SyntaxError: invalid syntax
[2025-03-31T22:01:09.239+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:01:56.017+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 45.548 seconds
[2025-03-31T22:03:13.189+0000] {processor.py:186} INFO - Started process (PID=3374) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:03:13.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:03:13.202+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:03:13.201+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:03:13.295+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:03:13.288+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.download_data import
                                     ^
SyntaxError: invalid syntax
[2025-03-31T22:03:13.297+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:03:13.442+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.287 seconds
[2025-03-31T22:05:22.423+0000] {processor.py:186} INFO - Started process (PID=3449) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:05:22.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:05:22.468+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:05:22.468+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:05:22.505+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:05:22.502+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.download_data import
                                     ^
SyntaxError: invalid syntax
[2025-03-31T22:05:22.520+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:05:22.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.247 seconds
[2025-03-31T22:05:52.746+0000] {processor.py:186} INFO - Started process (PID=3513) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:05:52.747+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:05:52.752+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:05:52.751+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:05:52.763+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:05:52.759+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.download_data import
                                     ^
SyntaxError: invalid syntax
[2025-03-31T22:05:52.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:05:52.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.069 seconds
[2025-03-31T22:06:22.936+0000] {processor.py:186} INFO - Started process (PID=3572) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:06:22.938+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:06:22.941+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:06:22.940+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:06:22.951+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:06:22.949+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.download_data import
                                     ^
SyntaxError: invalid syntax
[2025-03-31T22:06:22.952+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:06:23.000+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.073 seconds
[2025-03-31T22:06:53.111+0000] {processor.py:186} INFO - Started process (PID=3636) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:06:53.113+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:06:53.116+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:06:53.116+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:06:53.124+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:06:53.122+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1
    from scripts.download_data import
                                     ^
SyntaxError: invalid syntax
[2025-03-31T22:06:53.126+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:06:53.164+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.064 seconds
[2025-03-31T22:07:09.618+0000] {processor.py:186} INFO - Started process (PID=3648) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:07:09.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:07:09.623+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:07:09.622+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:07:09.646+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:07:09.644+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:07:09.647+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:07:09.725+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.128 seconds
[2025-03-31T22:07:40.361+0000] {processor.py:186} INFO - Started process (PID=3712) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:07:40.363+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:07:40.366+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:07:40.366+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:07:40.377+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:07:40.374+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:07:40.378+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:07:40.408+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.056 seconds
[2025-03-31T22:08:57.945+0000] {processor.py:186} INFO - Started process (PID=3777) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:08:57.955+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:08:57.965+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:08:57.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:08:57.990+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:08:57.980+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:08:57.999+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:08:58.094+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.176 seconds
[2025-03-31T22:09:56.603+0000] {processor.py:186} INFO - Started process (PID=3838) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:09:56.613+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:09:56.617+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:09:56.617+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:09:56.677+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:09:56.657+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:09:56.685+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:09:56.778+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.219 seconds
[2025-03-31T22:10:28.507+0000] {processor.py:186} INFO - Started process (PID=3899) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:10:28.510+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:10:28.525+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:10:28.524+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:10:28.552+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:10:28.549+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:10:28.554+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:10:28.630+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.159 seconds
[2025-03-31T22:12:58.829+0000] {processor.py:186} INFO - Started process (PID=3916) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:12:58.835+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:12:58.851+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:12:58.847+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:12:58.930+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:12:58.924+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:12:58.934+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:12:59.102+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.322 seconds
[2025-03-31T22:13:32.132+0000] {processor.py:186} INFO - Started process (PID=3977) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:13:32.165+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:13:32.173+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:13:32.172+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:13:32.221+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:13:32.211+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:13:32.225+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:13:32.414+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.376 seconds
[2025-03-31T22:14:09.787+0000] {processor.py:186} INFO - Started process (PID=4032) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:14:09.800+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:14:09.806+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:14:09.805+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:14:09.885+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:14:09.852+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:14:09.895+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:14:10.044+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.290 seconds
[2025-03-31T22:16:08.760+0000] {processor.py:186} INFO - Started process (PID=4053) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:16:08.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:16:08.781+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:16:08.781+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:16:08.816+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:16:08.812+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:16:08.818+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:16:08.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.137 seconds
[2025-03-31T22:18:59.250+0000] {processor.py:186} INFO - Started process (PID=4107) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:18:59.254+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:18:59.264+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:18:59.260+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:18:59.321+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:18:59.302+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:18:59.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:18:59.410+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.195 seconds
[2025-03-31T22:19:20.959+0000] {processor.py:186} INFO - Started process (PID=4162) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:19:20.961+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:19:20.964+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:19:20.963+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:19:20.989+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:19:20.985+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:19:20.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:19:21.037+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.090 seconds
[2025-03-31T22:20:42.002+0000] {processor.py:186} INFO - Started process (PID=4211) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:20:42.006+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:20:42.008+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:20:42.007+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:20:42.040+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:20:42.030+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:20:42.042+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:20:42.153+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.179 seconds
[2025-03-31T22:21:12.669+0000] {processor.py:186} INFO - Started process (PID=4273) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:21:12.671+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:21:12.674+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:21:12.673+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:21:12.694+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:21:12.690+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:21:12.695+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:21:12.740+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.082 seconds
[2025-03-31T22:21:43.292+0000] {processor.py:186} INFO - Started process (PID=4337) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:21:43.295+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:21:43.297+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:21:43.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:21:43.334+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:21:43.328+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 1, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:21:43.337+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:21:43.420+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.144 seconds
[2025-03-31T22:24:10.420+0000] {processor.py:186} INFO - Started process (PID=4389) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:24:10.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:24:10.458+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:24:10.458+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:24:10.539+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:24:10.523+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 6, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:24:10.553+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:24:10.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.328 seconds
[2025-03-31T22:24:41.700+0000] {processor.py:186} INFO - Started process (PID=4453) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:24:41.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:24:41.719+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:24:41.718+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:24:41.753+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:24:41.744+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 6, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:24:41.765+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:24:41.875+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.195 seconds
[2025-03-31T22:25:12.855+0000] {processor.py:186} INFO - Started process (PID=4517) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:25:12.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:25:12.860+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:25:12.859+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:25:12.890+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:25:12.885+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 6, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:25:12.893+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:25:12.931+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.087 seconds
[2025-03-31T22:25:43.704+0000] {processor.py:186} INFO - Started process (PID=4580) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:25:43.713+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:25:43.719+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:25:43.718+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:25:43.740+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:25:43.730+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 6, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:25:43.741+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:25:43.825+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.139 seconds
[2025-03-31T22:26:14.573+0000] {processor.py:186} INFO - Started process (PID=4643) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:26:14.575+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:26:14.583+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:26:14.582+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:26:14.600+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:26:14.598+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 6, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:26:14.601+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:26:14.654+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.092 seconds
[2025-03-31T22:26:51.250+0000] {processor.py:186} INFO - Started process (PID=4700) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:26:51.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:26:51.258+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:26:51.257+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:26:51.275+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:26:51.268+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 6, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:26:51.279+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:26:51.336+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.096 seconds
[2025-03-31T22:27:22.124+0000] {processor.py:186} INFO - Started process (PID=4758) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:27:22.130+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:27:22.134+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:27:22.134+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:27:22.182+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:27:22.177+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 6, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:27:22.185+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:27:22.271+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.159 seconds
[2025-03-31T22:27:52.756+0000] {processor.py:186} INFO - Started process (PID=4820) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:27:52.758+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:27:52.761+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:27:52.760+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:27:52.779+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:27:52.776+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 6, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:27:52.783+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:27:52.836+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.089 seconds
[2025-03-31T22:28:23.786+0000] {processor.py:186} INFO - Started process (PID=4884) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:28:23.788+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:28:23.791+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:28:23.790+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:28:23.804+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:28:23.799+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 6, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:28:23.805+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:28:23.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.073 seconds
[2025-03-31T22:28:54.620+0000] {processor.py:186} INFO - Started process (PID=4948) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:28:54.623+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:28:54.627+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:28:54.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:28:54.649+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:28:54.641+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 6, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:28:54.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:28:54.710+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.101 seconds
[2025-03-31T22:29:26.353+0000] {processor.py:186} INFO - Started process (PID=4996) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:29:26.360+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:29:26.365+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:29:26.363+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:29:26.392+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:29:26.386+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 6, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:29:26.395+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:29:26.485+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.149 seconds
[2025-03-31T22:31:13.723+0000] {processor.py:186} INFO - Started process (PID=5051) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:31:13.860+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:31:13.910+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:31:13.903+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:31:14.461+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:31:14.346+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 6, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:31:14.542+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:31:58.952+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 46.068 seconds
[2025-03-31T22:33:28.443+0000] {processor.py:186} INFO - Started process (PID=5124) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:33:28.444+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:33:28.451+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:33:28.450+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:33:28.505+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:33:28.491+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 6, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:33:28.507+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:33:28.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.221 seconds
[2025-03-31T22:35:08.944+0000] {processor.py:186} INFO - Started process (PID=5178) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:35:08.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:35:08.985+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:35:08.980+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:35:09.152+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:35:09.128+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 6, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:35:09.156+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:35:09.407+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.617 seconds
[2025-03-31T22:35:32.531+0000] {processor.py:186} INFO - Started process (PID=5233) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:35:32.535+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:35:32.540+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:35:32.540+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:35:32.564+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:35:32.559+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:35:32.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:35:32.602+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.082 seconds
[2025-03-31T22:36:03.398+0000] {processor.py:186} INFO - Started process (PID=5297) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:36:03.399+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:36:03.402+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:36:03.401+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:36:03.414+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:36:03.411+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:36:03.415+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:36:03.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.070 seconds
[2025-03-31T22:36:33.815+0000] {processor.py:186} INFO - Started process (PID=5361) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:36:33.817+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:36:33.821+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:36:33.820+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:36:33.845+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:36:33.842+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:36:33.846+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:36:33.874+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.077 seconds
[2025-03-31T22:37:04.447+0000] {processor.py:186} INFO - Started process (PID=5424) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:37:04.449+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:37:04.453+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:37:04.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:37:04.471+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:37:04.469+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:37:04.473+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:37:04.503+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.067 seconds
[2025-03-31T22:38:19.644+0000] {processor.py:186} INFO - Started process (PID=5481) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:38:19.645+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:38:19.653+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:38:19.652+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:38:19.720+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:38:19.708+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:38:19.722+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:38:19.922+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.312 seconds
[2025-03-31T22:38:50.268+0000] {processor.py:186} INFO - Started process (PID=5542) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:38:50.271+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:38:50.276+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:38:50.276+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:38:50.298+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:38:50.294+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:38:50.301+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:38:50.348+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.096 seconds
[2025-03-31T22:39:21.151+0000] {processor.py:186} INFO - Started process (PID=5606) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:39:21.154+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:39:21.159+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:39:21.158+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:39:21.173+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:39:21.170+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:39:21.174+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:39:21.234+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.098 seconds
[2025-03-31T22:40:07.471+0000] {processor.py:186} INFO - Started process (PID=5663) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:40:07.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:40:07.481+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:40:07.478+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:40:07.519+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:40:07.510+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:40:07.531+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:40:07.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.119 seconds
[2025-03-31T22:40:38.580+0000] {processor.py:186} INFO - Started process (PID=5724) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:40:38.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:40:38.585+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:40:38.584+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:40:38.608+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:40:38.596+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:40:38.627+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:40:38.727+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.167 seconds
[2025-03-31T22:41:09.978+0000] {processor.py:186} INFO - Started process (PID=5788) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:41:09.982+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:41:09.986+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:41:09.985+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:41:09.996+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:41:09.993+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:41:09.998+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:41:10.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.063 seconds
[2025-03-31T22:41:42.912+0000] {processor.py:186} INFO - Started process (PID=5851) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:41:42.917+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:41:42.926+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:41:42.924+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:41:42.959+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:41:42.949+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:41:42.962+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:41:43.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.157 seconds
[2025-03-31T22:42:13.318+0000] {processor.py:186} INFO - Started process (PID=5913) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:42:13.326+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:42:13.335+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:42:13.330+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:42:13.516+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:42:13.478+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:42:13.540+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:42:14.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 1.276 seconds
[2025-03-31T22:44:59.862+0000] {processor.py:186} INFO - Started process (PID=5919) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:44:59.867+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:44:59.876+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:44:59.871+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:44:59.954+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:44:59.942+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:44:59.960+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:45:00.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.252 seconds
[2025-03-31T22:45:30.228+0000] {processor.py:186} INFO - Started process (PID=5982) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:45:30.230+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:45:30.234+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:45:30.233+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:45:30.251+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:45:30.247+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:45:30.253+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:45:30.319+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.108 seconds
[2025-03-31T22:46:00.873+0000] {processor.py:186} INFO - Started process (PID=6045) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:46:00.875+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:46:00.885+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:46:00.883+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:46:00.939+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:46:00.937+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:46:00.940+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:46:01.011+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.150 seconds
[2025-03-31T22:46:31.550+0000] {processor.py:186} INFO - Started process (PID=6109) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:46:31.553+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:46:31.557+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:46:31.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:46:31.578+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:46:31.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:46:31.583+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:46:31.712+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.174 seconds
[2025-03-31T22:47:02.175+0000] {processor.py:186} INFO - Started process (PID=6173) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:47:02.177+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:47:02.185+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:47:02.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:47:02.227+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:47:02.204+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:47:02.231+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:47:02.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.134 seconds
[2025-03-31T22:47:34.449+0000] {processor.py:186} INFO - Started process (PID=6237) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:47:34.469+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:47:34.532+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:47:34.520+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:47:34.686+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:47:34.639+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:47:34.706+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:47:34.968+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.607 seconds
[2025-03-31T22:50:30.017+0000] {processor.py:186} INFO - Started process (PID=6299) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:50:30.296+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:50:30.316+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:50:30.312+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:50:32.789+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:50:31.879+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:50:32.833+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:50:34.168+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 4.279 seconds
[2025-03-31T22:51:04.342+0000] {processor.py:186} INFO - Started process (PID=6362) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:51:04.345+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:51:04.349+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:51:04.347+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:51:04.377+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:51:04.372+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:51:04.378+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:51:04.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.092 seconds
[2025-03-31T22:56:34.218+0000] {processor.py:186} INFO - Started process (PID=6433) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:56:34.235+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:56:34.260+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:56:34.259+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:56:34.303+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:56:34.298+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:56:34.313+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:56:34.460+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.263 seconds
[2025-03-31T22:57:04.694+0000] {processor.py:186} INFO - Started process (PID=6489) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:57:04.710+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:57:04.718+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:57:04.717+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:57:04.907+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:57:04.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:57:05.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:57:05.438+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.765 seconds
[2025-03-31T22:57:37.492+0000] {processor.py:186} INFO - Started process (PID=6553) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:57:37.498+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:57:37.502+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:57:37.500+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:57:37.620+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:57:37.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:57:37.629+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:57:37.789+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.333 seconds
[2025-03-31T22:58:09.025+0000] {processor.py:186} INFO - Started process (PID=6616) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:58:09.029+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:58:09.047+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:58:09.043+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:58:09.147+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:58:09.128+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:58:09.151+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:58:09.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.390 seconds
[2025-03-31T22:58:44.815+0000] {processor.py:186} INFO - Started process (PID=6674) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:58:44.821+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T22:58:44.894+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:58:44.864+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:58:45.106+0000] {logging_mixin.py:190} INFO - [2025-03-31T22:58:45.087+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T22:58:45.120+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T22:58:45.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.669 seconds
[2025-03-31T23:01:21.128+0000] {processor.py:186} INFO - Started process (PID=6717) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:01:21.183+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:01:21.383+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:01:21.259+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:01:22.161+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:01:21.835+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:01:22.317+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:04:40.111+0000] {processor.py:186} INFO - Started process (PID=6789) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:04:40.114+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:04:40.122+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:04:40.121+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:04:40.162+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:04:40.149+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:04:40.169+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:04:40.291+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.219 seconds
[2025-03-31T23:05:19.860+0000] {processor.py:186} INFO - Started process (PID=6843) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:05:19.864+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:05:19.881+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:05:19.881+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:05:19.937+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:05:19.921+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:05:19.946+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:05:20.136+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.339 seconds
[2025-03-31T23:36:12.636+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:36:12.644+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:36:12.668+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:36:12.667+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:36:12.682+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:36:12.679+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:36:12.686+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:36:12.829+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.213 seconds
[2025-03-31T23:36:52.740+0000] {processor.py:186} INFO - Started process (PID=136) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:36:52.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:36:52.750+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:36:52.749+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:36:52.833+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:36:52.829+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:36:52.836+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:36:52.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.213 seconds
[2025-03-31T23:37:54.470+0000] {processor.py:186} INFO - Started process (PID=151) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:37:54.491+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:37:54.527+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:37:54.521+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:37:54.578+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:37:54.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:37:54.596+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:37:54.900+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.519 seconds
[2025-03-31T23:38:25.117+0000] {processor.py:186} INFO - Started process (PID=213) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:38:25.122+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:38:25.133+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:38:25.132+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:38:25.159+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:38:25.151+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:38:25.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:38:25.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.097 seconds
[2025-03-31T23:39:59.001+0000] {processor.py:186} INFO - Started process (PID=243) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:39:59.013+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:39:59.019+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:39:59.018+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:39:59.037+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:39:59.029+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:39:59.038+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:39:59.100+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.116 seconds
[2025-03-31T23:42:43.121+0000] {processor.py:186} INFO - Started process (PID=73) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:42:43.136+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:42:43.163+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:42:43.158+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:42:43.193+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:42:43.190+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:42:43.210+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:42:43.381+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.314 seconds
[2025-03-31T23:43:19.839+0000] {processor.py:186} INFO - Started process (PID=137) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:43:19.849+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:43:19.860+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:43:19.859+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:43:19.885+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:43:19.877+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:43:19.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:43:20.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.245 seconds
[2025-03-31T23:45:00.697+0000] {processor.py:186} INFO - Started process (PID=165) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:45:00.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:45:00.703+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:45:00.702+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:45:00.713+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:45:00.711+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:45:00.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:45:00.765+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.080 seconds
[2025-03-31T23:45:30.991+0000] {processor.py:186} INFO - Started process (PID=221) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:45:30.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:45:31.019+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:45:31.019+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:45:31.073+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:45:31.051+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:45:31.075+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:45:31.181+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.208 seconds
[2025-03-31T23:46:04.479+0000] {processor.py:186} INFO - Started process (PID=290) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:46:04.481+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:46:04.486+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:46:04.485+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:46:04.499+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:46:04.494+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:46:04.500+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:46:04.565+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.096 seconds
[2025-03-31T23:48:19.862+0000] {processor.py:186} INFO - Started process (PID=350) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:48:19.868+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:48:19.882+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:48:19.878+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:48:19.926+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:48:19.919+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:48:19.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:48:20.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.204 seconds
[2025-03-31T23:48:51.080+0000] {processor.py:186} INFO - Started process (PID=414) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:48:51.085+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:48:51.095+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:48:51.091+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:48:51.191+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:48:51.179+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:48:51.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:48:51.251+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.191 seconds
[2025-03-31T23:49:21.309+0000] {processor.py:186} INFO - Started process (PID=478) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:49:21.311+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:49:21.314+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:49:21.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:49:21.323+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:49:21.321+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:49:21.324+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:49:21.410+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.111 seconds
[2025-03-31T23:49:51.585+0000] {processor.py:186} INFO - Started process (PID=542) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:49:51.590+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:49:51.595+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:49:51.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:49:51.672+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:49:51.651+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:49:51.693+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:49:51.830+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.290 seconds
[2025-03-31T23:50:22.119+0000] {processor.py:186} INFO - Started process (PID=602) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:50:22.129+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:50:22.141+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:50:22.140+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:50:22.169+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:50:22.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:50:22.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:50:22.288+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.204 seconds
[2025-03-31T23:50:53.120+0000] {processor.py:186} INFO - Started process (PID=665) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:50:53.125+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:50:53.130+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:50:53.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:50:53.149+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:50:53.146+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:50:53.152+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:50:53.260+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.153 seconds
[2025-03-31T23:55:49.100+0000] {processor.py:186} INFO - Started process (PID=699) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:55:49.102+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:55:49.106+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:55:49.106+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:55:49.117+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:55:49.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:55:49.119+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:55:49.178+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.094 seconds
[2025-03-31T23:57:28.783+0000] {processor.py:186} INFO - Started process (PID=754) to work on /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:57:28.784+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/premier_league_dag.py for tasks to queue
[2025-03-31T23:57:28.791+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:57:28.790+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:57:28.814+0000] {logging_mixin.py:190} INFO - [2025-03-31T23:57:28.805+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/premier_league_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_dag.py", line 10, in <module>
    from scripts.download_data import download_data
ModuleNotFoundError: No module named 'scripts.download_data'
[2025-03-31T23:57:28.817+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_dag.py
[2025-03-31T23:57:28.865+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/premier_league_dag.py took 0.092 seconds
